# Generated by Django 2.2.7 on 2019-11-30 07:11

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('contact_name', models.CharField(max_length=50)),
                ('email', models.EmailField(db_index=True, max_length=50)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=20, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suburb', models.CharField(db_index=True, max_length=10)),
                ('street_name', models.CharField(max_length=50)),
                ('postcode', models.BigIntegerField()),
                ('state', models.CharField(max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='python_test.Client')),
            ],
        ),
    ]
