# Generated by Django 2.2.7 on 2019-12-01 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('python_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='python_test.Client'),
        ),
    ]
